// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAu_RzEHeUHQkSBy7WjCFKgZbhs6ZH7YM',
    appId: '1:671924310086:web:f2b8c35eacb07671867a47',
    messagingSenderId: '671924310086',
    projectId: 'zimax-5ca71',
    authDomain: 'zimax-5ca71.firebaseapp.com',
    storageBucket: 'zimax-5ca71.firebasestorage.app',
    measurementId: 'G-0P2W6BYYSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT3d0eUqyYLNRzoSYshbYYCurEzOdoHlg',
    appId: '1:671924310086:android:b777faa8a48c5e77867a47',
    messagingSenderId: '671924310086',
    projectId: 'zimax-5ca71',
    storageBucket: 'zimax-5ca71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuzNg3rZzPK0habACBX1GE2SYSNtHJ9jg',
    appId: '1:671924310086:ios:6995cb8abd4c466b867a47',
    messagingSenderId: '671924310086',
    projectId: 'zimax-5ca71',
    storageBucket: 'zimax-5ca71.firebasestorage.app',
    iosBundleId: 'com.example.zimax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuzNg3rZzPK0habACBX1GE2SYSNtHJ9jg',
    appId: '1:671924310086:ios:6995cb8abd4c466b867a47',
    messagingSenderId: '671924310086',
    projectId: 'zimax-5ca71',
    storageBucket: 'zimax-5ca71.firebasestorage.app',
    iosBundleId: 'com.example.zimax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAu_RzEHeUHQkSBy7WjCFKgZbhs6ZH7YM',
    appId: '1:671924310086:web:d8a6ff559fc75116867a47',
    messagingSenderId: '671924310086',
    projectId: 'zimax-5ca71',
    authDomain: 'zimax-5ca71.firebaseapp.com',
    storageBucket: 'zimax-5ca71.firebasestorage.app',
    measurementId: 'G-CGNCBS9LP8',
  );
}
